### PR TITLE
Update to adhere to AirBnB Javascript style guide

### PR DESCRIPTION
**Pull request by ppourmand**
sup roonie, i was bored LOL.

### CODE REVIEW

**Comment by ppourmand** [comment]
0 to :100: real quick yo. I don't think I messed anything up (cuz it was all style stuff) but make sure before you merge, rofl.

**Comment by ajoseps** [comment]
Lol thanks dude haha. I'll try to check it out when I get back home from work today.



—

**Comment by ajoseps** [comment]
wait how do i approve it?

**Comment by ppourmand** [comment]
You'll have to merge it.

**Pull request merged**
